title: DiskPantry
description: Smoothini's Disk Pantry!
theme: just-the-docs

url: https://Smoothini.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark